### ISSUE TITLE
There is no any licence to protect your code.

### ISSUE THREAD

**Issue by lingyunmo** [2023village/Until#1]
I suggest you select a license and create a new License.md file to declare your license.

**Comment by 2023village** [comment]
我听不懂你在说啥，鼠鼠是业余的捏

**Comment by lingyunmo** [comment]
Alright,have a good day.

**Comment by 2023village** [comment]
但是不得不承认这听起来很棒

**Comment by lingyunmo** [comment]
You should think about it.That's good for you and your code.
